### ISSUE TITLE
Link with other applications

### ISSUE THREAD

**Issue by tdelmas** [nobelization/panoramax-mobile-app#105]
Could another application call this one, to take a picture of an element and get its url in return?

For example, an Application such as https://github.com/streetcomplete/StreetComplete could use it to get a picture of an OSM element, then attach that picture to the element with the appropriate OSM field. 

From https://github.com/streetcomplete/StreetComplete/issues/5939#issuecomment-2389646726 : 

> Another possibility would be to have SC invoke Panoramax app to take single picture via some intent or whatever (e.g. how it currently invokes StreetMeasure) and use that on OSM elements the mapper has chosen. Of course it would need code support on both sides, but would reduce code duplication much and solve account issues, who is responsible for uploaded pics etc.

**Comment by overflorian** [comment]
Hi, that would be, indeed, wonderful.
We will focus on releasing a V1 of the Panoramax app working correctly on its own and we might prioritize this later.
Of course, if there is a proper request (directly from Street Complete or any other significative app) to actually implement it, that would be a sign for us to move quicker.

**Comment by BDVGitHub** [comment]
[MapComplete](https://wiki.openstreetmap.org/wiki/MapComplete) uses Panoramax now for uploading there pictures.

**Comment by overflorian** [comment]
Indeed, and I think it shows that we should prioritize the opening of dedicated instances instead of joining URLs from the app. Therefore I'm closing this issue.
