### ISSUE TITLE
Change wording for the instance selection screen

### ISSUE THREAD

**Issue by overflorian** [nobelization/panoramax-mobile-app#113]
- [ ] Replace "Partager" for "Envoyer à"
- [ ] Implement separators and icons:

![image](https://github.com/user-attachments/assets/f00d01d1-a003-4656-87bf-8a563edd02f9)
Icones :
- geographic coverage: https://fonts.google.com/icons?selected=Material+Icons:public:&icon.query=worl&icon.size=24&icon.color=%235f6368
- licence: https://nextcloud.junglebus.io/index.php/s/dMonP3aFfR5CkiN

# OpenStreetMap France

- [ ] wording for the geographic coverage (logo "world"):

**Les photos peuvent être localisées dans le Monde entier**↲ 
Abstenez-vous néanmoins d'envoyer des photos dans les zones sensibles comme les terrains militaires.

- [ ] wording for the licence (licence logo):
 
**Les photos sont librement utilisables en open data**↲
N'oubliez pas de citer l'auteur de la photo et respectez les termes de la license [Creative Commons CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode).

# IGN
- [ ] Replace "Institut Géographique National" with "Institut national de l'information géographique et forestière"
- [ ] wording for the geographic coverage (logo "world") :

**Les photos doivent être localisées en France**↲ 
Les photos que vous envoyez à l'IGN doivent forcément être prises sur le territoire français (ce qui inclut les territoires ultra-marins) et en dehors de certaines zones sensibles comme les terrains militaires.

- [ ] wording for the licence (licence logo):

**Les photos sont librement utilisables en open data**↲
N'oubliez pas de citer l'auteur de la photo et respectez les termes de la license [etalab-2.0](https://github.com/panoramax/server/api/-/blob/develop/etalab-2.0).

**Comment by OtterWays** [comment]
Solved in pull request #124
