### ISSUE TITLE
Availability on F-Droid

### ISSUE THREAD

**Issue by natrius** [nobelization/panoramax-mobile-app#115]
Hello team,

Thank you for this project! I wanted to ask if there are any plans to make the app available on [F-Droid](https://f-droid.org/). There’s a [quickstart guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) that might help, and it’s generally recommended to follow the [Fastlane file structure](https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure) for descriptions, graphics, and screenshots.

If publishing directly to the F-Droid store isn't possible, setting up a personal F-Droid repository could also make updates easy for users.

This issue could perhaps be used to track progress if you choose to publish on F-Droid.

Best regards!

**Comment by overflorian** [comment]
Hi, thanks for your question.
YES! We will definitely publish our app on F-Droid.
In a near future, we will release at the same time on 4 channels: APK, F-Droid, App Store and Play Store.
