### ISSUE TITLE
v1.2.0-beta Error on opening.

### ISSUE THREAD

**Issue by chrisdebian** [nobelization/panoramax-mobile-app#126]
Please see the attached screenshot, not sure why the error happens. I'm using Android 15, on a Pixel 6.

Thanks for the new release.

Chris
chris_debian
![Screenshot_20241115-103054](https://github.com/user-attachments/assets/8292e333-e593-4d48-8c90-c76fe411369e)

**Comment by BDVGitHub** [comment]
Do you have your internet and GPS active? Does the app have permission to use GPS?

**Comment by chrisdebian** [comment]
Hi, @BDVGitHub.

Yes, internet and GPS are active. The previous version of Panoramax had permissions, and I wasn't prompted to change these, with the new version. 

When I select the Camera icon, the imagery collection screen is activated, as I would expect. 

I'm happy to submit logs for debugging, if you let me know how.

Thanks,

Chris

**Comment by BDVGitHub** [comment]
Good question, unfortunately I don't know the answer. @Jean-BaptisteC @OtterWays @cquest @overflorian can you tell how to see the logbook in the app for error handeling?
See Also #111 Thx

**Comment by BDVGitHub** [comment]
Just installed the latest version, on startup I get the same error message as @chrisdebian . Taking single photo or sequence succeeds, sending single photo or sequence fails. So there must be a bug in the programme somewhere. I am using a Samsung Galaxy S10, all apps in the play store are up to date as is my phone's software.

**Comment by BDVGitHub** [comment]
@chrisdebian for the moment I suggest you unistall the app en use the before the last one

**Comment by chrisdebian** [comment]
Thanks for looking into this, @BDVGitHub 

Chris

**Comment by overflorian** [comment]
Hi, I faced the same issue and the solution is simple: uninstall the previous version before installing the new one. 
Could you pleaee confirm it fixes the issue for you too?

**Comment by chrisdebian** [comment]
Still a problem for me. I installed the latest beta, over the previous release. I have just uninstalled the latest beta, then performed a new install of the latest beta. I still have the same error.

Sorry,

Chris

**Comment by BDVGitHub** [comment]
> Hi, I faced the same issue and the solution is simple: uninstall the previous version before installing the new one. Could you pleaee confirm it fixes the issue for you too?

Its working now thx

**Comment by BDVGitHub** [comment]
> Still a problem for me. I installed the latest beta, over the previous release. I have just uninstalled the latest beta, then performed a new install of the latest beta. I still have the same error.
> 
> Sorry,
> 
> Chris

Can you descibe what program you use to remove panoramax and how you remove the panoramax app?
Is it possible to check if all you're other apps are updated, do you now the brand and type off you're phone?

**Comment by chrisdebian** [comment]
Hi, @BDVGitHub. I uninstalled via Settings > Apps

![Screenshot_20241117-003046](https://github.com/user-attachments/assets/31048868-8131-4bfd-b096-db11e3db9b01)

All my apps and system updates have been applied. As per my opening post, I'm using Android 15, on a Pixel 6..

Thanks,

Chris

**Comment by overflorian** [comment]
> Is it maybe possible to place on eatch page on the Panoramax app te software version off the app that is used (so V1.1 or V1.2, ...)? 

Yes, it's planned in the upcoming menu https://github.com/nobelization/panoramax-mobile-app/issues/51

**Comment by BDVGitHub** [comment]
@overflorian On another github repo, I saw the following. When you report a problem by creating a topic in "issue" there is a template ready in the text field to report a problem, this text serves as a guide to report a problem. Below is a custom template that could be used here. Source [emhass issues](https://github.com/davidusb-geek/emhass/issues/new/choose)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Operation system**
 - Andriod
 - iOS
 - Windows
 -  ...

**Your hardware**
- Samsung, iPhone, OnePlus, ...
- Version

**Additional context**
Add any other context about the problem here.

**Comment by call-me-matt** [comment]
same for me. I upgraded from v1.1.2 and saw the error message on start. then uninstalled and re-installed v1.2.0  without success. Then removed v1.2.0 and reinstalled v1.1.2, removed data and cache, uninstalled it and installed v1.2.0 again - also not successful. I have the same effects as described above: https://github.com/nobelization/panoramax-mobile-app/issues/126#issuecomment-2480642953

**Comment by BDVGitHub** [comment]
@call-me-matt Would you know what brand and type of phone you are using? What is the software version of your phone, this information can usually be found in setting and then info phone

**Comment by call-me-matt** [comment]
Pixel 8, Android 15.

**Comment by overflorian** [comment]
The brand new release fixes this issue, see https://github.com/nobelization/panoramax-mobile-app/releases/tag/v1.2.1-beta

@BDVGitHub `On another github repo, I saw the following. When you report a problem by creating a topic in "issue" there is a template ready `
I am aware of this and will implement it as soon as we migrate to Gitlab (next month), thank you.

**Comment by chrisdebian** [comment]
Yep, the new release seems to have fixed it for me.

Chris

**Comment by overflorian** [comment]
nice.
