### ISSUE TITLE
Dynamises the default behaviour of the home page

### ISSUE THREAD

**Issue by stanlee974** [nobelization/panoramax-mobile-app#15]
This feature depends on the feature #12

Given that **no server URL is configured**,
Then we want to **open the configuration page** when the application is launched

**Comment by OtterWays** [comment]
It is preferable to create as little friction as possible in the user experience. If they are immediately asked to choose their instance and sign in, some users may abandon the process right from the beginning.

It is better to allow the user to take photos and view them first, and only when they are ready to send the photos, ask for the instance and connection.

Therefore, the order should be "camera" => "gallery" => send photos => authentication.

**Comment by u4y0u** [comment]
"It's best to allow the user to take photos and view them first, and only when ready to send the photos, request the instance and connection."

It would be interesting to be able to connect alternately to several instances according to the users' choice and to be able to memorize the different accounts for each instance.
Already knowing that an instance may be unavailable at any given time.
Personally I post my 360 images on the OSM instance and the others (fixed, drone, pedestrian, tests) on the IGN instance.

**Comment by overflorian** [comment]
Your suggestions regarding the favourite instance and login persistance have been implemented with https://github.com/nobelization/panoramax-mobile-app/issues/50

**Comment by overflorian** [comment]
The upcoming menu will solve the instance choice suggestion https://github.com/nobelization/panoramax-mobile-app/issues/51
