### ISSUE TITLE
Improve error message management

### ISSUE THREAD

**Issue by stanlee974** [nobelization/panoramax-mobile-app#16]
This feature depends on the feature #12

### On home page
  - Given that we haven't configured a server URL
  - Then we shouldn't display the loader. Instead, we should display a message prompting the user to configure the server URL: `Le serveur doit être configuré pour récupérer les collections.`
### On upload page
 - Given I reach the default timeout
 - Then this error message is displayed: `Le téléversement des photos a échoué`

**Comment by overflorian** [comment]
> Then we shouldn't display the loader. Instead, we should display a message prompting the user to configure the server URL: Le serveur doit être configuré pour récupérer les collections.

We decided not to display any photo gallery when the user is not logged-in. Instead, he/she directly faces a camera screen, allowing to take pictures with no in-between step.

> Then this error message is displayed: Le téléversement des photos a échoué

This will solve your issue: https://github.com/nobelization/panoramax-mobile-app/issues/119
