### ISSUE TITLE
[licence] add a licence 

### ISSUE THREAD

**Issue by lgrd** [nobelization/panoramax-mobile-app#18]
Hi there, 

hope you're fine. 

I think it could be cool to have a licence on this repo. What do you think of it ? :) 

If yes, which one ? MIT or GPL kind ?

**Comment by luifr10** [comment]
Closed by commit 02df206

**Comment by OtterWays** [comment]
As discussed verbally with @luifr10, we have chosen the AGPL license. 
@luifr10 , @Thithip , @Jean-BaptisteC : Since you have contributed to the code prior to the selection of this license, can you confirm that you agree with the choice of the AGPL?

**Comment by Jean-BaptisteC** [comment]
Yes no problem
