### ISSUE TITLE
Find a better AppID

### ISSUE THREAD

**Issue by Jean-BaptisteC** [nobelization/panoramax-mobile-app#24]
Today, you use this AppID:
https://github.com/nobelization/panoramax-mobile-app/blob/02df2069b691827f4de3d058fa9090887eb99642/android/app/build.gradle#L45

Some suggestions:
- `com.geovisio.panoramax_mobile`
- `com.panoramax_mobile`
- `panoramax_mobile.app`

Todo:
- [x] Update app_id in gradle scripts
- [x] Update package name in [Kotlin class](https://github.com/nobelization/panoramax-mobile-app/blob/02df2069b691827f4de3d058fa9090887eb99642/android/app/src/main/kotlin/com/example/panoramax_mobile/MainActivity.kt#L1)
- [x] Update the structure of Android directories
- [x] Updata app_id in integration tests

This change needs to be done before the first release because it's not possible to update the app. If app_id is different, the app is not updated, and a new app is installed.

**Comment by Jean-BaptisteC** [comment]
You need to do the same thing for IOS here
https://github.com/nobelization/panoramax-mobile-app/blob/02df2069b691827f4de3d058fa9090887eb99642/ios/Flutter/AppFrameworkInfo.plist#L10

**Comment by Jean-BaptisteC** [comment]
@luifr10 @OtterWays I think these changes need to be done on priority

**Comment by luifr10** [comment]
Indeed, I prefer `com.panoramax.app`
