### ISSUE TITLE
Instance selection screen 

### ISSUE THREAD

**Issue by OtterWays** [nobelization/panoramax-mobile-app#27]
We'd like to open the discussion about the instance selection screen.

Here are two proposals:

###  First proposal: A drop-down menu.

<p align="center">
<img width="390" alt="Choix de l'instance - long terme" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/8d7ed4b6-efdc-4f6f-8ef2-543ce545a17f"></center>
</p>

### Second proposal: Buttons with both logos.

<p align="center">
<img width="390" alt="Choix de l'instance - court terme" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/702b08a9-eade-42f6-b327-a45d8cc16642">
</p>

We think that the second solution would be the most suitable.

We also think that the term used should be reviewed, as the word "instance" could frighten the user.

We suggest: "Who do you want to send the photos to?".

**Comment by u4y0u** [comment]
It will be necessary to remember:
The data deposited will be published under the license
CC-BY-SA-4.0
The data deposited will be published under the license
etalab-2.0

**Comment by luifr10** [comment]
Personally, I do prefer the second layout, and I agree with avoiding the use of the term “instance”

**Comment by Coehill** [comment]
I also prefer the second layout, however it will not scale well as more Panoramax servers federate.  My suggestion is to go with layout #2 and then if a server admin wishes to add their instance, they can open an issue or later on, add a "custom" section.

**Comment by overflorian** [comment]
The second layout have been implemented, see https://github.com/nobelization/panoramax-mobile-app/issues/50

**Comment by mnalis** [comment]
> The second layout have been implemented, see https://github.com/nobelization/panoramax-mobile-app/issues/50

So, this issue can be closed?
