### ISSUE TITLE
Reduce area around button to take photos

### ISSUE THREAD

**Issue by Jean-BaptisteC** [nobelization/panoramax-mobile-app#31]
Area listener is more bigger than the round button to take photos, it's an inconvenient and can generates photos takes by mistake.
<img src="https://github.com/nobelization/panoramax-mobile-app/assets/87148630/428ae685-420d-4d5b-8631-342575f3d6f5" height=500 />

**Comment by OtterWays** [comment]
this issue was covered in #28
