### ISSUE TITLE
implement burst mode

### ISSUE THREAD

**Issue by OtterWays** [nobelization/panoramax-mobile-app#33]
When we walk, we want to be able to take photos automatically over a regular time interval rather than manually pressing the capture button.

**Comment by u4y0u** [comment]
"over a regular time interval" or over a distance from the previous shot to avoid duplicate photos during stops. ;-)

**Comment by OtterWays** [comment]
If we rely on distance traveled instead of time, we may risk missing some photos until the GPS detects the resumption of the movement. We won't have this problem with regular time intervals. Additionally, if we plan to be able to change the time between two photos, it will allow us to adapt the photo capture to our mode of transportation (e.g., car or pedestrian).

In the future, we can consider automatically deleting detected duplicates.

**Comment by u4y0u** [comment]
It is true that each method has its advantages and disadvantages.

The distance difference method is linked to the precision of GPS which can be subject to interference like any radio frequency system. it is common to see deviations from the route not only when passing through tunnels, but also in the narrow streets of old neighborhoods, in the heart of large cities in the shade of buildings, under the tree cover in the forest, or sometimes even in open ground without really knowing why.
On the other hand, it is extremely practical when traveling by vehicle to see the shot automatically adapt to the speed and not notice any gaps in the shot.

The timer method allows regular spacing of sockets only if the speed of movement is constant, which is unfortunately very rare when traveling in built-up areas and even worse in the heart of a city. On the other hand, it is perfectly suited to open axes.
This method requires regular use of start/stop by the user to avoid unnecessary snapshots during stops.

Personally, it is this timer method that I use the most when shooting 360° for Panaramax, but it could be interesting to leave the choice to the users depending on the terrain they have to explore.

**Comment by Coehill** [comment]
This tool may be useful for de-duplicating images:
https://github.com/Stefal/Photo_filter

A blend of a timer-based approach to not miss images due to GPS detection, along with adjusting the timer based on speed could be a good approach.  I suspect that some amount of de-duplication may be needed in each scenario.
