### ISSUE TITLE
Android APK release for testing?

### ISSUE THREAD

**Issue by Coehill** [nobelization/panoramax-mobile-app#44]
Is this project at a state where the developers would be comfortable with releasing an Android APK file?  I would be interested in testing the app and reporting bugs.  Of course, I understand that this is still in development and I would not expect a finished product.  If you are not yet comfortable with releasing an alpha or beta APK, then feel free to close this issue. :)

**Comment by Jean-BaptisteC** [comment]
It's too early, selection of instance and connection to Panoramax is not yet implemented
I suggest you to follow this topic on forum to stay tuned to know first beta is ready to be tested :)
https://forum.geocommuns.fr/t/appli-mobile-panoramax/1521

**Comment by Coehill** [comment]
Thank you

**Comment by Coehill** [comment]
The first beta release is now available. Closing issue.

https://github.com/nobelization/panoramax-mobile-app/tags
