### ISSUE TITLE
Error during camera is opened

### ISSUE THREAD

**Issue by Jean-BaptisteC** [nobelization/panoramax-mobile-app#59]
<img src="https://github.com/nobelization/panoramax-mobile-app/assets/87148630/8b92f675-4f30-4634-8e6c-00aa879aceaa" height=400 />

How reproduce:
- Start app
- Lock the device
- Unlock the device
- On Panoramax, launch the camera -> red screen appears during 1 second

Pixel 6 - Android 14

**Comment by Coehill** [comment]
Related to: https://github.com/nobelization/panoramax-mobile-app/issues/78

**Comment by Jean-BaptisteC** [comment]
Pop-up it's not the problem, it's the red screen

**Comment by overflorian** [comment]
What about now with https://github.com/nobelization/panoramax-mobile-app/releases/tag/v1.1.2-beta ?

**Comment by Jean-BaptisteC** [comment]
Not able to reproduce on latest version
