### ISSUE TITLE
change the panoramax logo

### ISSUE THREAD

**Issue by OtterWays** [nobelization/panoramax-mobile-app#71]
The Panoramax logo present in the application is not up to date. The one to use is [https://beta.gouv.fr/img/startups/vues-immersives-libres.png](https://beta.gouv.fr/img/startups/vues-immersives-libres.png)

**Comment by Coehill** [comment]
I am seeing the following logos for the app icon and the app launch screen, respectively.

Feel free to close the ticket if this is what you were expecting.

![App Icon](https://github.com/nobelization/panoramax-mobile-app/assets/13023025/36b32181-fd75-4374-a4e4-7cf9f8c74f88)
![Launch Screen](https://github.com/nobelization/panoramax-mobile-app/assets/13023025/1a8361d2-e23a-4677-8ded-25fd50fd0493)

**Comment by chrisdebian** [comment]
Has this been implemented, now? Can we close this?

Chris
