### ISSUE TITLE
v1.0.0-beta Feedback

### ISSUE THREAD

**Issue by chrisdebian** [nobelization/panoramax-mobile-app#77]
Hi, all.

I've just installed the app on a Pixel 6 with Android 14. I can confirm that I can switch between Photo and Sequence mode, but can't see any menus or options, so not sure what to do next. It would be good if I could turn in debugging, so I can send logs, if needed.

Well done!

Chris | chris_debian

**Comment by Jean-BaptisteC** [comment]
Menus and options are not implemented for now.
For now, you can:
- take photos or sequence
- Press envelope button to send to an instance

**Comment by chrisdebian** [comment]
Thank you. Looking good.

Chris

**Comment by chrisdebian** [comment]
> Menus and options are not implemented for now. For now, you can:
> 
> * take photos or sequence
> * Press envelope button to send to an Panoramax instance

@Jean-BaptisteC 

I couldn't find where apk releases are, could you point me to the latest?

Is there a list of Panoramax instances, ideally ones that share images with OSM.

Thanks,

Chris

**Comment by Jean-BaptisteC** [comment]
Releases is available here https://github.com/nobelization/panoramax-mobile-app/releases
And list of instance is available on panoramax.fr

**Comment by chrisdebian** [comment]
Thank you. I did check 'Releases', and I'll look out for future one.

Thank you.

Chris

**Comment by call-me-matt** [comment]
I tried the beta today and am quite happy with it. Will keep it installed and start contributing to the project. Well done!

Here some feedback:
 - Before uploading a sequence, it would be nice to delete certain pictures from the overview screen or even delete the complete sequence. I tried the app first at home and then had to clear the app cache to prevent the test pictures being published. Same happened to a friend.
 - It would be nice to see the sequence upload size, maybe with an option to upload later (when wifi is available)

Here some bugs I experienced:
 - Upload progress stays at 0 pictures until it is complete
 - After uploading a sequence, I get a view of the map and also my profile with my sequences. But once left, no way to get back there.
 - One upload failed, I see the sequence online with 0 pictures. In the application, I cannot find a way to upload the pictures again.

**Comment by Jean-BaptisteC** [comment]
Cc @overflorian

**Comment by call-me-matt** [comment]
I liked a lot that there was an APK added to the resources of this release. Please continue this with current releases. @OtterWays

**Comment by fnordson** [comment]
I have to admit, I'm a bit confused due to the lack of a menu.  
I had to leave the app while uploading and find no way to go there again and see if everything is up. 
Either I miss something or it would be nice if it could be added.   
Other than that, I agree with [call-me-matt](https://github.com/call-me-matt) here. Got to the same issues. The broken upload is the reason I wanted to have a look again.

**Comment by overflorian** [comment]
```
I have to admit, I'm a bit confused due to the lack of a menu.
I had to leave the app while uploading and find no way to go there again and see if everything is up.
Either I miss something or it would be nice if it could be added.
```

Hi, in the [planned menu](https://github.com/nobelization/panoramax-mobile-app/issues/51), there is nothing about upload.
Does the new "My sequence" view fit with this need?

**Comment by overflorian** [comment]
@call-me-matt all your feedback are valid.
Here's an update about their respective status:

> Before uploading a sequence, it would be nice to delete certain pictures from the overview screen or even delete the complete sequence.

That's implemented now

> It would be nice to see the sequence upload size, maybe with an option to upload later (when wifi is available)

Both these are on the roadmap, not developed yet

> When not moving, the app should not continue taking pictures. Alternatively, a pause function would do.

That's on the roadmap too

> You could consider using the wide angle camera by default. (so does mapillary)

Very useful, I add it the roadmap too

> Upload progress stays at 0 pictures until it is complete

Wired. Do you still face this issue with the latest release?

> After uploading a sequence, I get a view of the map and also my profile with my sequences. But once left, no way to get back there.

The new gallery interface allows you to get back to the sequence by just clicking on the picture

> One upload failed, I see the sequence online with 0 pictures. In the application, I cannot find a way to upload the pictures again.

I agree that it's concerning.
We should develop a "not uploaded yet" section. That's on the roadmap but for later.

**Comment by chrisdebian** [comment]
@overflorian Hi, is the roadmap public? Using my phone, so it's not easy to search for it.

Thanks,

Chris

**Comment by call-me-matt** [comment]
Thank you for your feedback. I am really looking forward to the next versions.
I know it is still beta, but must say that it is already quite good quality.
Will create individual issues for remaining bugs if they persist to make it easier to track.

**Comment by overflorian** [comment]
Thank you for your feedback again.

@chrisdebian I have published the current roadmap here: https://community.openstreetmap.org/t/panoramax-app-for-android/120510/7
In the future, we plan to share to priorities directly on the repository just after we will migrate to Gitlab in few weeks.

**Comment by chrisdebian** [comment]
Thank you

**Comment by chrisdebian** [comment]
@call-me-matt Matt, did you manage to check to see if separate issues had been raised? If they have, we can probably close this issue.

Thanks,

Chris

**Comment by call-me-matt** [comment]
> @call-me-matt Matt, did you manage to check to see if separate issues had been raised? If they have, we can probably close this issue.

the critical points have been addressed by overflorian. for me it is fine to close this issue, no need to track every comment as issue.
