### ISSUE TITLE
"GPS Disabled" when location is available

### ISSUE THREAD

**Issue by RedAuburn** [nobelization/panoramax-mobile-app#78]
When launching the app, i get the error "GPS disabled", even though i have location fix in other apps.

it also overlays itself, looks like a new popup is added every time a location request fails, even though the popup is already displayed

Panoramax version: 1.0 Beta
Device: Oneplus 9 Pro
OS: LineageOS 20 + MicroG

**Comment by Coehill** [comment]
> When launching the app, i get the error "GPS disabled", even though i have location fix in other apps.
> 
> it also overlays itself, looks like a new popup is added every time a location request fails, even though the popup is already displayed
> 
> Panoramax version: 1.0 Beta Device: Oneplus 9 Pro OS: LineageOS 20 + MicroG

What are your location permissions set to for Panoramax from App Info > Permissions > Location?

**Comment by RedAuburn** [comment]
> What are your location permissions set to for Panoramax from App Info > Permissions > Location?
wow.. i'm surprised i didn't think to check that 😅 
it was not allowed. i don't remember a popup asking for permission though, i'll double-check with a fresh reinstall.


> Additionally, are you able to reproduce this bug in the same was as Issue #59?
nope, camera works fine for me :)

**Comment by RedAuburn** [comment]
can confirm that no location request popup happens

**Comment by overflorian** [comment]
I believe that it's the expected behaviour. Therefore can we close this issue?

**Comment by RedAuburn** [comment]
is it really expected behaviour not to prompt the user for position access?? If so, i guess it can be closed, but it's not good UX IMO

**Comment by overflorian** [comment]
No it's not; sorry, I misunderstood. We'll investigate.
Also, we will display visually to the user the fact that GPS is disabled, stopping him/her to start recording see https://github.com/nobelization/panoramax-mobile-app/issues/85

**Comment by overflorian** [comment]
Hi @RedAuburn could you please check if you still face this issue with the latest release? It should be fix now https://github.com/nobelization/panoramax-mobile-app/releases/tag/v1.1.2-beta

**Comment by RedAuburn** [comment]
sorry, i completely forgot about this. Testing the new beta, it seems to be working perfectly! many thanks :)
