### ISSUE TITLE
please also publish `.apk` for V1.1.0-beta

### ISSUE THREAD

**Issue by mnalis** [nobelization/panoramax-mobile-app#98]
[v1.0.0-beta](https://github.com/nobelization/panoramax-mobile-app/releases/tag/release-beta) had not only source, but also binary ready made `.apk` available for download on GitHub.

[v1.1.0-beta](https://github.com/nobelization/panoramax-mobile-app/releases/tag/v1.1.0-beta) unfortunately has only source. Could someone please also add prebuilt `.apk` file to that GitHub release page, so majority of the users can test it? Thanks!

**Comment by call-me-matt** [comment]
I was also waiting for it. It's now available!
